name: Build and Publish Docker Images to Github Container Registry
on:
  push
jobs:
  publish-ubuntu-16-04:
    env:
      DOCKER_IMAGE=ubuntu-16.04
    name: Build and Push Docker image ${{ DOCKER_IMAGE }} to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./${{ DOCKER_IMAGE }}.docker
          tags: ghcr.io/tpm2-software/${{ DOCKER_IMAGE }}:latest
  publish-ubuntu-18-04:
    env:
      DOCKER_IMAGE=ubuntu-18.04
    name: Build and Push Docker image ${{ DOCKER_IMAGE }} to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./${{ DOCKER_IMAGE }}.docker
          tags: ghcr.io/tpm2-software/${{ DOCKER_IMAGE }}:latest
  publish-ubuntu-20-04:
    env:
      DOCKER_IMAGE=ubuntu-20.04
    name: Build and Push Docker image ${{ DOCKER_IMAGE }} to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./${{ DOCKER_IMAGE }}.docker
          tags: ghcr.io/tpm2-software/${{ DOCKER_IMAGE }}:latest
  publish-opensuse-leap-15-2:
    env:
      DOCKER_IMAGE=opensuse-leap-15.2
    name: Build and Push Docker image ${{ DOCKER_IMAGE }} to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./${{ DOCKER_IMAGE }}.docker
          tags: ghcr.io/tpm2-software/${{ DOCKER_IMAGE }}:latest
  publish-opensuse-leap:
    env:
      DOCKER_IMAGE=opensuse-leap
    name: Build and Push Docker image ${{ DOCKER_IMAGE }} to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./${{ DOCKER_IMAGE }}.docker
          tags: ghcr.io/tpm2-software/${{ DOCKER_IMAGE }}:latest
   publish-fedora-30:
    env:
      DOCKER_IMAGE=fedora-30
    name: Build and Push Docker image ${{ DOCKER_IMAGE }} to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./${{ DOCKER_IMAGE }}.docker
          tags: ghcr.io/tpm2-software/${{ DOCKER_IMAGE }}:latest
   publish-fedora-32:
    env:
      DOCKER_IMAGE=fedora-32
    name: Build and Push Docker image ${{ DOCKER_IMAGE }} to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./${{ DOCKER_IMAGE }}.docker
          tags: ghcr.io/tpm2-software/${{ DOCKER_IMAGE }}:latest
